# Generated by Django 3.2.6 on 2022-08-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
