# Generated by Django 2.2.16 on 2022-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_auto_20220727_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Юзернейм'),
            preserve_default=False,
        ),
    ]
