# Generated by Django 2.2.16 on 2022-07-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
